- README.md
i updated every link i could find from https://github.com/Esri/arcgis-clone-js to https://github.com/Esri/solution.js but apparently i forgot the most important one.
it'd probably be a good idea to rename the actual repo before you merge this and make sure Travis is still happy.
> rename repo in README

- packages/common/src/restHelpers.ts
- packages/feature-layer/src/featureServiceHelpers.ts
- packages/simple-types/src/webmap.ts
Fixes:
templatizing webmap layer references
visible field mismatch between source view and new view
feature service name undefined in some cases...will now use name or title
> feature service updates

- packages/feature-layer/src/featureServiceHelpers.ts
- packages/feature-layer/test/featureServiceHelpers.test.ts
> handle view field domain and defQueries issue

- packages/common/src/resourceHelpers.ts
- packages/common/test/resourceHelpers.test.ts
- packages/common/test/restHelpers.test.ts
- packages/simple-types/src/simple-types.ts
- packages/simple-types/test/simple-types.test.ts
background: integration test was failing because form data wasn't preserving|using extension on blob filename. Without the extension, addResources rejects the add with the misleading message "File type not allowed for addResources", even if the blob had an accepted MIME type.
> addResources requires extension

- packages/common/src/featureServiceHelpers.ts
- packages/common/test/featureServiceHelpers.test.ts
- packages/creator/src/creator.ts
- packages/feature-layer/src/feature-layer.ts
- packages/feature-layer/test/feature-layer.test.ts
- packages/simple-types/test/webmap.test.ts
@MikeTschudi  Added arguments so field templatization could be turned on at a later time but set them with defaults so no changes should be required from create app until a point where we may want them on again.
> remove field templatization

- package-lock.json
- packages/common/examples/convertExtent/package-lock.json
- packages/common/examples/copyItemInfo/package-lock.json
- packages/common/examples/copySolutions/package-lock.json
- packages/common/examples/getItemInfo/package-lock.json
- packages/common/package-lock.json
- packages/common/test/mocks/agolItems.ts
- packages/creator/examples/createSolutionFromGroup/package-lock.json
- packages/creator/examples/createSolutionFromItem/package-lock.json
- packages/creator/package-lock.json
- packages/creator/src/createItemTemplate.ts
- packages/creator/test/createItemTemplate.test.ts
- packages/deployer/examples/deploySolution/package-lock.json
- packages/deployer/package-lock.json
- packages/feature-layer/package-lock.json
- packages/file/package-lock.json
- packages/group/package-lock.json
- packages/simple-types/package-lock.json
- packages/simple-types/src/simple-types.ts
- packages/storymap/package-lock.json
- packages/viewer/package-lock.json
Finds the solution thumbnail item (tag "deploy.thumbnail") and adds it as created solution's thumbnail rather than as a solution item. (#128)
And changed flagging of unsupported item type to help its removal from created solution.  (In particular, aimed at Code Attachments (#128).)
> Intercept solution thumbnail item in group

- packages/common/src/restHelpersGet.ts
- packages/common/test/restHelpersGet.test.ts
- packages/group/src/group.ts
- packages/group/test/group.test.ts
It appears that group thumbnails have to be handled differently than item thumbnails: one has to send the actual thumbnail [(Group parameters' `thumbnail`)](https://developers.arcgis.com/rest/users-groups-and-items/common-parameters.htm) rather than a URL to a thumbnail. #283
> Changed group thumbnail handling

- packages/common/src/restHelpers.ts
- we are leveraging the `portal` property of the `portal.ISearchOptions` in our Bridge can we add it to the `common.searchGroupContents` function as proposed in this PR?
> add additional option to searchGroupContents wrapper

- package-lock.json
- package.json
- packages/common/package-lock.json
- packages/creator/package-lock.json
- packages/deployer/package-lock.json
- packages/deployer/package.json
- packages/deployer/src/deploySolutionFromTemplate.ts
- packages/deployer/src/deployer.ts
- packages/deployer/src/deployerUtils.ts
- packages/deployer/src/index.ts
- packages/deployer/test/deploySolutionFromTemplate.test.ts
- packages/deployer/test/deployer.test.ts
- packages/deployer/test/deployerUtils.test.ts
- packages/feature-layer/package-lock.json
- packages/file/package-lock.json
- packages/group/package-lock.json
- packages/simple-types/package-lock.json
- packages/storymap/package-lock.json
- packages/viewer/package-lock.json
Addresses #305 but even if ya'll happy with it, pls do not merge it yet :)
**Note**: this spiraled a bit, and I'm not at all fixed on the naming anything changed in this, or location of the additional util fn's I created... so ya'll likely have better ideas where some of this stuff should live or what it should be named.
Changes the `solutionItemId: string` param of `deploySolution(...)` to `maybeModel: string| IModel`, and handles both cases.
Adds `_getSolutionTemplateItem(..)` that takes the `maybeModel` and either fetches the item + data if it's a string, or returns the passed in model, if it's an `IModel`.
This PR also refactors `deploySolution(...)` to use a flat promise chain, and hoists out much the between-steps logic into helpers in `deployerUtils`. 
Since I was working in the …
> [DNM] Allow Solution Model or Id to be passed into deploySolution

- CHANGELOG.md
- packages/common/package-lock.json
- packages/common/package.json
- packages/common/src/index.ts
- packages/common/src/interfaces.ts
- packages/common/src/migrations/is-legacy-solution.ts
- packages/common/src/migrations/upgrade-three-dot-zero.ts
- packages/common/src/migrations/upgrade-two-dot-three.ts
- packages/common/src/migrations/upgrade-two-dot-two.ts
- packages/common/src/migrator.ts
- packages/common/test/migrations/is-legacy-solution.test.ts
- packages/common/test/migrations/upgrade-three-dot-zero.test.ts
- packages/common/test/migrations/upgrade-two-dot-three.test.ts
- packages/common/test/migrations/upgrade-two-dot-two.test.ts
- packages/common/test/migrator.test.ts
- packages/creator/src/creator.ts
- packages/creator/test/creator.test.ts
- packages/deployer/src/deployerUtils.ts
This is just setting up the schema versioning system.
Adds `item.properties.schemaVersion` and runs migrations if needed.
Currently it just stamps schemaVersion as 3 unless the app encounters a solution w/ Hub specific typeKeywords - which it should not b/c the hub specific items lack the `Template` keyword.
It is one connected into the main workflows in `deployer` - but ideally we'd have a fn `getSolutionItem(...): Promise<ISolutionItem>`, put the migration in there and have everything use that fn.
> Add solution schemaVersion, migrations

- packages/common/src/generalHelpers.ts
- packages/creator/src/creator.ts
- packages/creator/test/createItemTemplate.test.ts
- packages/creator/test/creator.test.ts
- packages/deployer/src/deploySolutionItems.ts
- packages/simple-types/src/simple-types.ts
#307
Thought these main entry points for create and deploy would be nice spots for some error logs to come through. 
In regards to the extra handeling in the callback for failed. Seems like this is a good spot to get a more detailed message about the failure before the template is removed. 
So for the case of a web map that fails to create because one of it's layers have been deleted we get a message about the FS with the invalid url and we also get the webmap item id from the main create entry point error.
> add some error logging to the console

- CHANGELOG.md
- package.json
- packages/common/package-lock.json
- packages/common/package.json
- packages/common/src/index.ts
- packages/common/src/interfaces.ts
- packages/common/src/migrations/is-legacy-solution.ts
- packages/common/src/migrations/upgrade-three-dot-zero.ts
- packages/common/src/migrations/upgrade-two-dot-three.ts
- packages/common/src/migrations/upgrade-two-dot-two.ts
- packages/common/src/migrator.ts
- packages/common/test/libs.test.ts
- packages/common/test/migrations/is-legacy-solution.test.ts
- packages/common/test/migrations/upgrade-three-dot-zero.test.ts
- packages/common/test/migrations/upgrade-two-dot-three.test.ts
- packages/common/test/migrations/upgrade-two-dot-two.test.ts
- packages/common/test/migrator.test.ts
- packages/creator/src/creator.ts
- packages/creator/test/creator.test.ts
- packages/deployer/package-lock.json
- packages/deployer/package.json
- packages/deployer/src/deployerUtils.ts
- umd-base-profile.js
in which we have resolved the upstream issues in hub.js so that:
a) Blobs are only handled in browsers, and this eliminates the `stream` import
b) the node typescript `util` library is not used, thus eliminating the `util` import
c) we have resolved some of the import paths, resolving the circular dependency 
Locally, this also changes the UMD build to treat the `@esri/hub-*` packages as external imports, so UMD packages using solution-js will also need to bring in the `hub-common` umd package. I'm not sure how that works in terms of changed to other apps, but in order to support sites and pages, we will be bringing in more of the `@esri/hub-*` packages. 
This builds clean, and passes all tests w. 100% coverage for me on 12.16.1, and 10.16.1
--- 
This is just setting up the schema …
> F/268 solution schema versioning (Take 2)

- karma.conf.js
- package-lock.json
- package.json
- packages/common/package-lock.json
- packages/common/src/dependencies.ts
- packages/common/src/featureServiceHelpers.ts
- packages/common/src/generalHelpers.ts
- packages/common/src/interfaces.ts
- packages/common/src/resourceHelpers.ts
- packages/common/src/restHelpers.ts
- packages/common/src/restHelpersGet.ts
- packages/common/src/templatization.ts
- packages/creator/package-lock.json
- packages/deployer/package-lock.json
- packages/feature-layer/package-lock.json
- packages/file/package-lock.json
- packages/group/package-lock.json
- packages/simple-types/package-lock.json
- packages/simple-types/src/simple-types.ts
- packages/storymap/package-lock.json
- packages/viewer/package-lock.json
- tsconfig.test.json
#329 
* Fall back from es6 to es2015 just for tests to continue to use spyOn
* Switched to single imports for common to prepare for es6 with spyOn and sinon.stub; recommendation to make it easier to insert stubs
* Adjusted package and rebuilt package-locks
> Adjusted repo for ts 3.9.2

- packages/common/src/index.ts
- packages/common/src/migrations/upgrade-two-dot-four.ts
- packages/common/src/resourceHelpers.ts
- packages/common/src/resources/add-resource-from-blob.ts
- packages/common/src/resources/copy-resource.ts
- packages/common/src/resources/get-blob.ts
- packages/common/src/resources/index.ts
- packages/common/src/restHelpersGet.ts
- packages/common/test/migrations/upgrade-two-dot-four.test.ts
- packages/common/test/resourceHelpers.test.ts
- packages/common/test/resources/copy-resources.test.ts
- packages/common/test/resources/get-blob.test.ts
- packages/common/test/restHelpersGet.test.ts
- packages/deployer/src/deploySolutionItems.ts
- packages/deployer/test/deployer.test.ts
- packages/file/test/file.test.ts
- packages/form/package.json
- packages/hub-types/src/helpers/_post-process-site.ts
- packages/hub-types/src/hub-page-processor.ts
- packages/hub-types/src/hub-site-processor.ts
- packages/hub-types/test/helpers/_post-process-site.test.ts
- packages/hub-types/test/hub-page-processor.test.ts
- packages/hub-types/test/hub-site-processor.test.ts
**Note:** This moved & refactored some low-level blob functions:
- `add-resource-from-blob.ts`
- `copy-resource.ts`
- `get-blob.ts`
While I'm pretty sure everything is solid (all previous tests pass) everyone working in this project should be watching out for oddities related to fetching blobs or copying resources as blobs.
--- 
Hub Related Changes:
- Handle Resources in pre-existing Hub-created Solution Templates
- Site item get's id's of all created items in it's `item.properties.children` array
- Site and Page processors check state via progress callback 
- they can early exit
- they can remove created items if informed at the end
Also addresses:
- more refactoring of fn's out of massive modules into separate files, which enable consistent use of `spyOn` vs having to let code run …
> Hub Site/Page Resources

- packages/common/src/interfaces.ts
- packages/common/src/migrations/upgrade-two-dot-five.ts
- packages/common/src/migrator.ts
- packages/common/test/migrations/upgrade-two-dot-five.test.ts
- packages/common/test/migrations/upgrade-two-dot-four.test.ts
- packages/common/test/migrator.test.ts
- packages/form/src/form.ts
- packages/form/src/helpers/build-create-params.ts
- packages/form/src/helpers/create-item-from-hub-template.ts
- packages/form/src/helpers/create-survey.ts
- packages/form/src/helpers/encode-survey-form.ts
- packages/form/src/helpers/is-hub-form-template.ts
- packages/form/test/form.test.ts
- packages/form/test/helpers/build-create-params.test.ts
- packages/form/test/helpers/create-item-from-hub-template.test.ts
- packages/form/test/helpers/create-survey.test.ts
- packages/form/test/helpers/encode-survey-form.test.ts
This PR brings in the bulk of the custom Hub Survey Solution processing logic. I'll be submitting one more survey-related PR to address the following:
1. Update the Feature Service & Form items to apply what couldn’t be passed through to the API
2. Investigate/resolve a CORS preflight error related to the S123 API create request (doesn't fail deployment)
3. add a processed template result entry for the Feature Service
4. test updates for 1 & 3
> Custom Hub Survey processing logic

- package-lock.json
- packages/hub-types/src/helpers/_post-process-page.ts
- packages/hub-types/src/helpers/_post-process-site.ts
- packages/hub-types/src/hub-page-processor.ts
- packages/hub-types/src/hub-site-processor.ts
- packages/hub-types/test/helpers/_post-process-page.test.ts
- packages/hub-types/test/helpers/_post-process-site.test.ts
- packages/hub-types/test/hub-page-processor.test.ts
- packages/hub-types/test/hub-site-processor.test.ts
- packages/web-experience/package-lock.json
- packages/web-experience/src/helpers/convert-web-experience-to-template.ts
- packages/web-experience/src/helpers/create-web-experience-model-from-template.ts
- packages/web-experience/src/helpers/create-web-experience.ts
- packages/web-experience/src/helpers/get-experience-subdomain.ts
- packages/web-experience/src/web-experience-processor.ts
- packages/web-experience/test/fixtures/exb-map-and-images.ts
- packages/web-experience/test/helpers/convert-web-experience-to-template.test.ts
- packages/web-experience/test/helpers/create-web-experience-model-from-template.test.ts
- packages/web-experience/test/helpers/create-web-experience.test.ts
- packages/web-experience/test/helpers/get-experience-subdomain.test.ts
- packages/web-experience/test/helpers/get-web-experience-dependecies.test.ts
- packages/web-experience/test/web-experience-processor.test.ts
Also lands "final pass" interpolation for Sites and Pages as per #366 
The only remaining `/* istanbul ignore next */`'s in the Hub-Types package is for the `convertItemToTemplate` functions, which have not been implemented yet.
> ExB and Hub packages at 100% coverage

- demos/createSolution/index.html
- package-lock.json
- packages/creator/src/createItemTemplate.ts
- packages/hub-types/src/helpers/create-hub-request-options.ts
- packages/hub-types/src/helpers/replace-item-ids.ts
- packages/hub-types/src/hub-page-processor.ts
- packages/hub-types/src/hub-site-processor.ts
- packages/hub-types/test/helpers/create-hub-request-options.test.ts
- packages/hub-types/test/helpers/replace-item-ids.test.ts
- packages/hub-types/test/hub-page-processor.test.ts
- packages/hub-types/test/hub-site-processor.test.ts
- packages/storymap/src/helpers/create-storymap.ts
- packages/storymap/src/storymap-processor.ts
- packages/storymap/test/helpers/create-storymap.test.ts
- packages/web-experience/src/helpers/create-web-experience.ts
- packages/web-experience/src/web-experience-processor.ts
- packages/web-experience/test/helpers/create-web-experience.test.ts
Implements `convertItemToTemplate` for Hub Types
Also:
- move ExB and StoryMaps to the output folder
Closes #374
> Convert Site and Page to Template

- package-lock.json
- package.json
- packages/common/package-lock.json
- packages/creator/package-lock.json
- packages/deployer/package-lock.json
- packages/feature-layer/package-lock.json
- packages/file/package-lock.json
- packages/form/package-lock.json
- packages/group/package-lock.json
- packages/hub-types/package-lock.json
- packages/simple-types/package-lock.json
- packages/storymap/package-lock.json
- packages/viewer/package-lock.json
- packages/web-experience/package-lock.json
- umd-base-profile.js
Reverted commit that switched from rollup-plugin-node-builtins & rollup-plugin-node-globals to rollup-plugin-node-polyfills.
Commit c98b7e5d14e1f4361c02a66f735caf71b2a8ba9a
Complete rebuild of all node_modules, package_jsons, dist/ and I'm not seeing the buffer-es6 throw.
> Reverted rollup-plugin commit

- .travis.yml
Currently, we manually run `npm run docs:deploy` (defined as "npm run docs:build && node support/deploy-doc-site.js") after creating a tagged release in `master`.  Would like to have docs deploy automatically as appears to be done in arcgis-rest-js.
> Updated Travis CI config to trigger doc build

- demos/addResource/package-lock.json
- demos/compareJSON/package-lock.json
- demos/convertExtent/package-lock.json
- demos/copyItemInfo/package-lock.json
- demos/copySolutions/package-lock.json
- demos/createFolder/package-lock.json
- demos/createSolution/package-lock.json
- demos/deploySolution/index.html
- demos/deploySolution/package-lock.json
- demos/getGUID/package-lock.json
- demos/getGroupInfo/package-lock.json
- demos/getItemInfo/package-lock.json
- demos/getSolutions/package-lock.json
- demos/implementedTypes/package-lock.json
- demos/polyfillExplorer/package-lock.json
- demos/sanitizeGroupItems/package-lock.json
- demos/sanitizer/package-lock.json
- demos/searchGroupCategories/package-lock.json
- package-lock.json
- packages/common/package-lock.json
- packages/common/package.json
Back in February, `arcgis-html-sanitizer` [changed it's build system](https://github.com/Esri/arcgis-html-sanitizer/pull/51) to output ES6 modules instead of ES5 modules.
This has some upsides when all consumers of the library are able to drop IE11 support, but most packages will ship ES5 modules, not ES6.
While the Solutions App itself does not need to support IE11, Hub currently does. In order to bring Solution.js into Hub, we need to use the 2.1.1 version, which is what this PR does.
It also uses ES5 syntax in `index.html` in the `/demos/deploySolution` app so that it can run in IE11 (and is how I tested this)
> Use ArcGIS-Html-Sanitizer v2.1.1

- docs/build-typedoc.js
- packages/common/src/migrations/is-legacy-solution.ts
- packages/common/src/migrations/upgrade-three-dot-zero.ts
- packages/common/src/migrations/upgrade-two-dot-five.ts
- packages/common/src/migrations/upgrade-two-dot-four.ts
- packages/common/src/migrations/upgrade-two-dot-six.ts
- packages/common/src/migrations/upgrade-two-dot-three.ts
- packages/common/src/migrations/upgrade-two-dot-two.ts
- packages/common/src/restHelpers.ts
Two doc changes:
- hide anything marked `@private` from being shown in the docs
- sort the lists in the doc. Due to some other aspects of the doc system, this sort is not "perfect" but much better than it was. Really addressing this requires a more intensive refactor of `docs/build-typedoc.ts` which I don't have time for now.
Also marks the migration functions as `@private`
*Note* the `getItemBase` is above `_cacheFieldInfo`
As far as building + deploying doc on merge to master - that's something we have to do in Github and I'll try to peek at that over the weekend
> Update Doc Site Generator

- packages/creator/src/helpers/add-content-to-solution.ts
- packages/creator/test/creator.test.ts
- packages/deployer/src/deploySolutionItems.ts
- packages/deployer/test/deploySolutionItems.test.ts
- packages/deployer/test/deployer.test.ts
During the creation and deployment processes, report a failing item id to the console when the progress function learns about it rather than waiting to the end.
> Report a failing item id as soon as possible

- demos/createSolution/src/getItemInfo.ts
- demos/deploySolution/src/getItemInfo.ts
- demos/getItemInfo/src/main.ts
- demos/searchGroupCategories/src/main.ts
Some items contain HTML in their JSON, which can interfere with the display of demos such as getItemInfo. Escaped the HTML in JSON to fix this problem and for general safety.
> Escaped text displayed in demos

- packages/deployer/src/deployerUtils.ts
- packages/deployer/test/deployerUtils.test.ts
Before the `Solution` item type was available Hub used `Web Mapping Application` with the `hubSolutionTemplate` keyword. Turns out there are a lot of these in PROD, so we need to allow them into the deployer.
This just opens up `isSolutionTemplateItem` to allow these through.
> Allow older hub Solution Template items

- packages/common/src/migrations/apply-schema.ts
- packages/common/src/migrations/upgrade-two-dot-one.ts
- packages/common/src/migrations/upgrade-two-dot-zero.ts
- packages/common/src/migrator.ts
- packages/common/test/migrations/apply-schema.test.ts
- packages/common/test/migrations/upgrade-two-dot-one.test.ts
- packages/common/test/migrations/upgrade-two-dot-zero.test.ts
- packages/common/test/migrator.test.ts
- packages/deployer/src/deployerUtils.ts
This adds more migrations to allow Hub to send the oldest of hub "solution" templates through this processing chain.
It also applies migrations to any solution model objects passed into `deploySolution(maybeModel, ...)`. This greatly streamlines things for applications which need to pre-process the solution i.e. translating content in the templates
I'm going to try to "link" this branch into the opendata-ui app, to verify, but these are the same fn's we run in the Hub app, so I'm pretty confident :)
> Ensure Solutions can load and migrate the oldest hub templates

- packages/storymap/src/helpers/create-storymap.ts
- packages/storymap/test/helpers/create-storymap.test.ts
A typo resulted in the draft, and oembed resources uploading `undefined` vs the actual content. The platform would of course report success, but... nothing would actually be uploaded. 
The current PROD version of StoryMaps is not tolerant of a missing `draft-<datestamp>.json` file, and thus fails like this:
By hacking in node_modules I was able to locate the issue and test the fix that is applied in this PR... here is an example of a StoryMap that was deployed via this code:
[https://storymaps.arcgis.com/stories/dd77c029b70148d7938ba567cdfd3c9f](https://storymaps.arcgis.com/stories/dd77c029b70148d7938ba567cdfd3c9f)
Not sure if we need to do some form of hotfix for Prod, but the Hub team needs this in a release asap fo we can move forward with our transition over to using Solution.js …
> [StoryMap] Ensure uploading of actual blob vs undefined

- packages/common/src/libConnectors.ts
- packages/common/test/libConnectors.test.ts
JSZip behaves differently creating folders in Chrome and Firefox. Changed approach so that it works in both.
> Changed folder handling to support Firefox

- packages/common/src/restHelpers.ts
#424 
sourceServiceFields is a hash that was used for handeling domain field names and never should have been going out with update calls.
> remove sourceServiceFields

- .gitignore
- packages/hub-types/src/helpers/create-hub-request-options.ts
- packages/hub-types/test/helpers/create-hub-request-options.test.ts
The `createHubRequestOptions` helper function in `hub-types` was not handling Portal correctly, resulting in an error being thrown from a underlying hub.js function.
Verified this works by running the Solution.js pipeline, in Hub, backed by a Portal 10.8.1 instance
Closes #439
> Fix `createHubRequestOptions` for Portal`

- packages/creator/src/helpers/add-content-to-solution.ts
- packages/creator/test/helpers/add-content-to-solution.test.ts
- packages/hub-types/package.json
When a group is included in the templating process, the system attempts to include all the items shared to the group. However, not all items can be templated - i.e. `Hub Initiative` items. 
This PR just adds a guard into the `_postProcessGroupDependencies` function so it does not attempt to process the dependantTemplate if it's not found in the templates array.
> Guard against non-templated items in Group deps

- packages/common/src/migrations/upgrade-two-dot-four.ts
- packages/common/test/migrations/upgrade-two-dot-four.test.ts
Got a bug from a customer indicating that some Hub Solutions had asset names w/ folders, but the actual resources did not have that folder structure.
This pr removes the folder from the name during the 2.3 -> 2.4 transform
Verified on Prod in Hub, using the customer's org and live Solution items
> Remove folders from asset names during 2.3 -> 2.4 schema transform

- packages/common/src/generalHelpers.ts
- packages/common/src/restHelpers.ts
- packages/common/src/restHelpersGet.ts
- packages/common/test/restHelpersGet.test.ts
- packages/creator/test/creator.test.ts
- packages/deployer/src/deploySolutionFromTemplate.ts
- packages/deployer/src/deployer.ts
- packages/deployer/src/deployerUtils.ts
- packages/deployer/test/deploySolutionFromTemplate.test.ts
- packages/deployer/test/deployer.test.ts
#535 
* Improved handling of missing Solution item metadata
* Don't fetch or upload metadata.xml for the solution item if the Solution's id is not a GUID (for Hub)
* Don't send the thumbnailUrl for the deployed Solution item if its `.thumbnail` property is undefined
> Improved handling of missing Solution item metadata

- packages/common/src/categories.ts
- packages/common/src/index.ts
- packages/common/src/restHelpers.ts
- packages/common/test/categories.test.ts
PR https://github.com/Esri/arcgis-rest-js/pull/686 would have done this completely within arcgis-rest-js, but that PR isn't going to be merged.
This PR provides patch code that, coupled with PR https://github.com/Esri/arcgis-rest-js/pull/777, will support searching by ANDing categories.
This PR's code will have no effect until (and if) PR 777 is accepted, a build is created, and the new arcgis-rest-js version is added to solution.js.
cf. [issue 466](https://github.com/ArcGIS/solution-deployment-app/issues/466#issuecomment-724166139)
> Added support for searching by ANDing categories

- packages/common/test/mocks/agolItems.ts
- packages/creator/src/creator.ts
- packages/creator/src/helpers/add-content-to-solution.ts
- packages/creator/test/helpers/add-content-to-solution.test.ts
- packages/simple-types/test/helpers/create-item-from-template.test.ts
Look for item references in places such as an item's description and add those references to the item's dependencies list.
#534
Also added three-letter code for Web Experience Template and renamed `_addContentToSolution` because it's an external function.
> Add item references to an item's dependencies

- packages/form/src/helpers/create-item-from-hub-template.ts
- packages/form/src/helpers/post-process-survey.ts
- packages/form/test/helpers/create-item-from-hub-template.test.ts
- packages/form/test/helpers/post-process-survey.test.ts
[166968](https://esriarlington.tpondemand.com/entity/166968-regression-survey-solution-templates-fail-to).
We're experiencing intermittent deployment failures for Hub survey templates. When the error occurs, the message is `Item does not exist or is inaccessible` and is related to the logic that moves the `Form` & `Feature Service` items and deletes their original folder created by the S123 API. Despite the  REST `move` API returning a success response for both items, the `Form` remains in the S123 folder and gets deleted when the original S123 folder gets deleted. The actual error is thrown from a downstream `update` call for the `Form` in the post processing logic.
This PR resolves in the intermittent failures by moving the calls that move the items & delete the original S123 folder …
> 166968 - Fix intermittent Hub survey template deployment failures.

- packages/common/src/migrations/upgrade-two-dot-seven.ts
- packages/common/src/migrator.ts
- packages/common/test/migrations/upgrade-two-dot-seven.test.ts
- packages/common/test/migrator.test.ts
We ran into some issues w/ very old Hub templates, and needed to add another 2.x migration to address the problem.
> fix: add migration to address very old hub templates

- packages/hub-types/src/hub-page-processor.ts
- packages/hub-types/src/hub-site-processor.ts
- packages/storymap/src/storymap-processor.ts
- packages/web-experience/src/web-experience-processor.ts
The deployment code for four item types--Web Experience, Hub Site Application, Hub Page, and StoryMap--isolated the routines from side effects to make the routines more robust and testable.
This turns out to be a problem when embedding the code into Angular, which has its own definition for a Promise--a definition that contains circular references and thus breaks during certain JavaScript options.
This PR changes the four item types to allow side effects. Not an enhancement, but it does permit Angular to host solution.js.
#598
> Modified item handling to support Angular

- README.md
- packages/hub-types/src/hub-page-processor.ts
- packages/hub-types/src/hub-site-processor.ts
- packages/hub-types/test/hub-page-processor.test.ts
- packages/hub-types/test/hub-site-processor.test.ts
A continuation of #604, #605, and #607 for hub pages and hub sites, which do not support supplying a thumbnail file during item creation.
> Patch thumbnails for deployed hub items

- demos/package-lock.json
- package-lock.json
- packages/hub-types/package-lock.json
- packages/hub-types/package.json
- packages/hub-types/src/helpers/create-hub-request-options.ts
- packages/hub-types/test/helpers/create-hub-request-options.test.ts
- packages/hub-types/test/hub-page-processor.test.ts
- packages/hub-types/test/hub-site-processor.test.ts
The hub-types package had been pulling the user from `templateDictionary.user` and using that to construct the `IHubRequestOptions` hash that's needed by the hub-js functions that create sites etc.
However, the groups attached to that user are currently filtered to only the groups the user owns. This decreses the count of groups, which is a problem when a user is a member of 512 groups... the Hub code checks how many groups they belong to (via user.groups), and since it's filtered, it returns a number that's lower and then it tries to create more groups... and the api calls fail... and things go badly.
In this change, we always fetch the user from the platform, and use that instead.
> Fetch user when creating IHubRequestOptions

- packages/creator/src/helpers/add-content-to-solution.ts
- packages/creator/test/helpers/add-content-to-solution.test.ts
#630
_postProcessGroupDependencies and postProcessWorkforceTemplates both can intentionally remove items from the dependency array.
> dependency issue

- packages/common/src/deleteSolution.ts
- packages/common/test/deleteSolution.test.ts
See https://github.com/Esri/solution.js/issues/624#issuecomment-845987971
Does not delete folder if it contains a non-Solution item.
After all deletions, the code queries the folder for its contents. Because sometimes AGO will report an item successfully deleted, yet will still later return that item during a query, the code checks the successful deletions against the list of items in the Solution. If all items returned from a query are in the list of successfully deleted items, then the code goes ahead with deleting the folder even though it nominally contains items.
> Delete deployment folder when deleting a solution

- packages/deployer/src/deploySolutionFromTemplate.ts
- packages/deployer/src/helpers/sortTemplates.ts
- packages/deployer/test/helpers/sortTemplates.test.ts
Sorting a deployed Solution's templates into build order broke the handling of shared items and post processing (see https://github.com/Esri/solution.js/issues/650#issuecomment-854235929).
This PR fixes the problem.
> Handle reused items

- demos/src/getFormattedItemInfo.ts
- packages/common/src/completeItem.ts
- packages/common/test/completeItem.test.ts
- packages/creator/src/helpers/add-content-to-solution.ts
- packages/creator/test/helpers/add-content-to-solution.test.ts
1. fixed error handling when copySolutions has problems fetching the Solution that it just created
2. only look in an item's data section when seeking additional dependencies
See https://github.com/Esri/solution.js/issues/652#issuecomment-866964432
> Improve handling of postprocessing dependencies

- packages/group/src/group.ts
- packages/group/test/group.test.ts
Thumbnail is already part of group item definition, so it is unnecessary to try to fetch the thumbnail again, which wasn't working.  Also have to be careful with thumbnail file because adlib call during cloning breaks the file.
#681
> Fixed thumbnail sent during group creation

- packages/common/src/deleteHelpers/deleteSolutionContents.ts
- packages/common/src/deleteSolution.ts
- packages/common/src/restHelpers.ts
- packages/common/test/deleteSolution.test.ts
- packages/common/test/restHelpers.test.ts
- packages/deployer/src/deploySolutionFromTemplate.ts
- packages/deployer/src/deploySolutionItems.ts
- packages/deployer/test/deploySolutionFromTemplate.test.ts
- packages/deployer/test/deploySolutionItems.test.ts
- packages/deployer/test/deployer.test.ts
Instead of just deleting all items and groups in the Solution, delete in reverse order of creation (feature service views before their feature services) and use hub.js to delete Hub items.
#675
> Improve cleanup when Solution fails to deploy

- packages/common/src/interfaces.ts
- packages/common/src/resourceHelpers.ts
- packages/common/src/resources/copyAssociatedFiles.ts
- packages/common/src/resources/copyResourceIntoZip.ts
- packages/common/src/resources/createCopyResults.ts
- packages/common/src/resources/getItemResourcesFilesFromPaths.ts
- packages/common/src/resources/getItemResourcesPaths.ts
- packages/common/src/resources/index.ts
- packages/common/test/resourceHelpers.test.ts
- packages/common/test/resources/copyAssociatedFiles.test.ts
- packages/creator/src/createItemTemplate.ts
- packages/creator/src/helpers/add-content-to-solution.ts
* Changed sending of resources to a Solution during Solution creation. Previously, only the resources from a single item were zipped. Now, resources are accumulated from all items and are zipped together.
* Fetch resources from source items to make sure that they exist before adding a reference to them in the created Solution. Previously, a reference to an item's resource was added to the item's template and fetching occurred later--when the item's resources were to be fetched, zipped, and sent to the created Solution. Now, the resource file itself is collected when the item's template is created (not just the path to it) and only zipping and sending occur at the end of the creation process.
see issue #679
> Fix resource handling during creation to skip non-existent files

- packages/common/src/restHelpersGet.ts
Firefox is handling "application/json" files in a way that causes them to be rejected. This change treats "application/json" the same as "text/plain".
> Modify MIME type handling for Firefox

- demos/deploySolution/data/appConfig.js
- demos/deploySolution/index.html
- demos/src/deploy-solution-main.ts
The deploySolution demo needed to be configured to support the change in the name of the property holding the primary group of Solution templates as well as to include the property for the additional (Enterprise) group of templates.
The two sets are each in alphabetical order by title. The sets are displayed in the dropdown sequentially to make the source of the template clearer.
> Updated deploySolution demo with additional Solutions group

- packages/common/src/resourceHelpers.ts
- packages/common/test/resourceHelpers.test.ts
Function wasn't properly handling prefixed filenames, e.g., "a/b/file.txt"
> Fix updating resource

- demos/compareJSON/package-lock.json
- demos/compareJSON/package.json
- demos/compareSolutions/package-lock.json
- demos/compareSolutions/package.json
- demos/copyItemInfo/package-lock.json
- demos/copyItemInfo/package.json
- demos/copySolutions/package-lock.json
- demos/copySolutions/package.json
- demos/createSolution/package-lock.json
- demos/createSolution/package.json
- demos/deleteSolution/package-lock.json
- demos/deleteSolution/package.json
- demos/deploySolution/package-lock.json
- demos/deploySolution/package.json
- demos/getItemInfo/package-lock.json
- demos/getItemInfo/package.json
- demos/implementedTypes/package-lock.json
- demos/implementedTypes/package.json
- demos/verifySolution/package-lock.json
- demos/verifySolution/package.json
- package-lock.json
- package.json
Locking TypeScript to the 5.2.x series because 5.3.x breaks the build for the tests.  Tried many ways to get the tests to build, but was unsuccessful.
> Lock major & minor TypeScript version

- README.md
- packages/common/README.md
- packages/creator/README.md
- packages/deployer/README.md
- packages/feature-layer/README.md
- packages/file/README.md
- packages/form/README.md
- packages/group/README.md
- packages/hub-types/README.md
- packages/simple-types/README.md
- packages/storymap/README.md
- packages/velocity/README.md
- packages/viewer/README.md
- packages/web-experience/README.md
- packages/workflow/README.md
Because we no longer use Coveralls (we use Codecov), these values aren't being updated. Codecov does not appear to do package-level coverage.
> Remove references to Coveralls

- demos/compareJSON/package-lock.json
- demos/compareSolutions/package-lock.json
- demos/copyItemInfo/package-lock.json
- demos/copySolutions/package-lock.json
- demos/createSolution/package-lock.json
- demos/deleteSolution/package-lock.json
- demos/deploySolution/package-lock.json
- demos/getItemInfo/package-lock.json
- demos/implementedTypes/package-lock.json
- demos/verifySolution/package-lock.json
- package-lock.json
- packages/common/src/generalHelpers.ts
- packages/common/src/interfaces.ts
- packages/common/src/workflowHelpers.ts
- packages/common/src/zip-utils.ts
- packages/common/test/generalHelpers.test.ts
- packages/common/test/mocks/agolItems.ts
- packages/common/test/restHelpers.test.ts
- packages/common/test/zip-utils.test.ts
- packages/deployer/src/deploySolutionItems.ts
- packages/deployer/src/helpers/zip-utils.ts
- packages/deployer/test/deploySolutionItems.test.ts
- packages/deployer/test/helpers/zip-utils.test.ts
- packages/group/test/group.test.ts
- packages/simple-types/src/helpers/convert-item-to-template.ts
- packages/simple-types/src/helpers/zip-utils.ts
- packages/simple-types/test/helpers/convert-item-to-template.test.ts
- packages/simple-types/test/helpers/zip-utils.test.ts
- packages/simple-types/test/quickcapture.test.ts
- packages/simple-types/test/webmappingapplication.test.ts
Also some refactoring and renaming to clarify what's going on.
#1317
> Fixed support for Survey123 webhooks

- packages/deployer/src/deploySolutionItems.ts
- packages/form/src/post-process.ts
- packages/form/test/post-process.test.ts
> Removed XLSX swizzling for now

- packages/common/src/interfaces.ts
Trivial editing change; significant functional change
> Changed spatial ref `required` property to match existing manual settings

- package-lock.json
- package.json
retire.js reported a security flaw in the axios package:
> axios 1.7.3 has known vulnerabilities: severity: high; summary: Server-Side Request Forgery in axios, CVE: CVE-2024-39338, githubID: GHSA-8hc4-vh64-cxmj; https://github.com/advisories/GHSA-8hc4-vh64-cxmj https://nvd.nist.gov/vuln/detail/CVE-2024-39338 https://github.com/axios/axios/issues/6463 https://github.com/axios/axios/pull/6539 https://github.com/axios/axios/pull/6543 https://github.com/axios/axios/commit/6b6b605eaf73852fb2dae033f1e786155959de3a https://github.com/axios/axios https://github.com/axios/axios/releases https://github.com/axios/axios/releases/tag/v1.7.4 https://jeffhacks.com/advisories/2024/06/24/CVE-2024-39338.html
axios is only used by lerna, which we're using at its latest version.  Updated axios, and lerna …
> Updated axios due to security flaw

- packages/common/src/index.ts
- packages/common/src/resources/getItemResourcesPaths.ts
- packages/common/src/webtoolHelpers.ts
- packages/common/test/resources/getItemResourcesPaths.test.ts
- packages/common/test/webtoolHelpers.test.ts
- packages/creator/src/createItemTemplate.ts
- packages/creator/src/helpers/add-content-to-solution.ts
- packages/simple-types/src/helpers/convert-item-to-template.ts
- packages/web-tool/src/web-tool-processor.ts
- packages/web-tool/test/web-tool-processor.test.ts
https://devtopia.esri.com/WebGIS/solution-deployment-apps/issues/100
Still need to investigate one GPServer url that isn't found in the exb app.
> Gp service updates

- package-lock.json
- package.json
The Field Maps team reported this to me when they attempted to leverage solutions.js:
> “After pulling in solutions.js we see a few things coming up in our security scans (Vulnerability: fast-xml-parser @ < 4.4.1 <https://github.com/ArcGIS/field-apps-web/issues/4189#top> ) is this something you have seen?”
> Update npm package fast-xml-parser
