Esri/solution.js

- packages/common/src/restHelpers.ts
- packages/common/test/mocks/agolItems.ts
- packages/feature-layer/test/feature-layer.test.ts
- packages/simple-types/src/simple-types.ts
- packages/simple-types/src/workforce.ts
- packages/simple-types/test/simple-types.test.ts
- packages/simple-types/test/workforce.test.ts
@MikeTschudi this is not 100% complete but should be very close. Wanted to get in the work before I head out for the week.
> workforce project

- README.md
- package-lock.json
- package.json
- packages/common/test/generalHelpers.test.ts
- packages/simple-types/src/simple-types.ts
- packages/simple-types/src/webmappingapplication.ts
- packages/simple-types/test/webmappingapplication.test.ts
> Fixed Web AppBuilder code attachment

- packages/deployer/src/deployer.ts
- packages/feature-layer/src/featureServiceHelpers.ts
- packages/feature-layer/test/featureServiceHelpers.test.ts
- packages/simple-types/src/simple-types.ts
> Use the orgs default extent and spatial reference for feature service and views

- packages/common/src/restHelpers.ts
- packages/common/test/restHelpers.test.ts
- packages/deployer/src/deployer.ts
- packages/feature-layer/src/feature-layer.ts
- packages/feature-layer/src/featureServiceHelpers.ts
- packages/feature-layer/test/feature-layer.test.ts
- packages/feature-layer/test/featureServiceHelpers.test.ts
> project org extent

- packages/deployer/src/deployer.ts
- packages/deployer/test/deployer.test.ts
> change extent to comma delimited

- package-lock.json
- package.json
- packages/common/README.md
- packages/common/package-lock.json
- packages/common/package.json
- packages/common/src/interfaces.ts
- packages/common/src/resourceHelpers.ts
- packages/common/test/mocks/templates.ts
- packages/common/test/mocks/utils.ts
- packages/common/test/resourceHelpers.test.ts
- packages/creator/package-lock.json
- packages/creator/package.json
- packages/creator/src/creator.ts
- packages/creator/test/creator.test.ts
- packages/deployer/package-lock.json
- packages/deployer/package.json
- packages/deployer/src/deployer.ts
- packages/deployer/test/deployer.test.ts
- packages/feature-layer/package-lock.json
- packages/feature-layer/package.json
- packages/simple-types/package-lock.json
- packages/simple-types/package.json
- packages/simple-types/src/webmappingapplication.ts
- packages/storymap/package-lock.json
- packages/storymap/package.json
- packages/viewer/package-lock.json
- packages/viewer/package.json
Housekeeping work:
* merged interfaces into single file
* added interface doc
* updated packages for security and for enabling audit checks
One unexpected change: the extent for the two items in the "can deploy webmap with dependencies" deployer test are returned as undefined rather than null. For the time being, change expectations to undefined so that tests pass.
> Package updates

- packages/common/src/generalHelpers.ts
- packages/common/src/restHelpers.ts
- packages/common/test/mocks/templates.ts
- packages/common/test/restHelpers.test.ts
- packages/common/test/templatization.test.ts
- packages/creator/src/createSolutionTemplate.ts
- packages/creator/test/createSolutionItem.test.ts
- packages/deployer/src/deployer.ts
- packages/deployer/test/deployer.test.ts
- packages/feature-layer/src/featureServiceHelpers.ts
- packages/feature-layer/test/feature-layer.test.ts
- packages/feature-layer/test/featureServiceHelpers.test.ts
- packages/simple-types/src/dashboard.ts
- packages/simple-types/src/simple-types.ts
- packages/simple-types/src/webmap.ts
- packages/simple-types/src/webmappingapplication.ts
- packages/simple-types/src/workforce.ts
- packages/simple-types/test/dashboard.test.ts
- packages/simple-types/test/simple-types.test.ts
- packages/simple-types/test/webmap.test.ts
- packages/simple-types/test/webmappingapplication.test.ts
- packages/simple-types/test/workforce.test.ts
- packages/storymap/test/storymap.test.ts
> template changes

- package-lock.json
- packages/common/examples/convertExtent/TypeScript/package-lock.json
- packages/common/examples/copyItemInfo/TypeScript/package-lock.json
- packages/common/examples/copySolutions/TypeScript/package-lock.json
- packages/common/examples/getItemInfo/TypeScript/package-lock.json
- packages/common/package-lock.json
- packages/common/package.json
- packages/common/src/featureServiceHelpers.ts
- packages/common/src/generalHelpers.ts
- packages/common/src/interfaces.ts
- packages/common/src/resourceHelpers.ts
- packages/common/src/restHelpers.ts
- packages/common/src/restHelpersGet.ts
- packages/common/src/templatization.ts
- packages/common/test/restHelpers.test.ts
- packages/creator/package-lock.json
- packages/creator/src/createSolutionTemplate.ts
- packages/creator/src/creator.ts
- packages/deployer/package-lock.json
- packages/deployer/src/deployer.ts
- packages/feature-layer/package-lock.json
- packages/feature-layer/src/feature-layer.ts
- packages/simple-types/package-lock.json
- packages/simple-types/src/simple-types.ts
- packages/simple-types/test/simple-types.test.ts
- packages/simple-types/test/webmappingapplication.test.ts
- packages/storymap/package-lock.json
- packages/viewer/package-lock.json
Removed remaining `rest_*` calls (cf. #132)
> Isolate the arcgis-rest-* libraries to the `common` package, continued

- packages/common/src/interfaces.ts
- packages/common/src/restHelpers.ts
- packages/common/src/restHelpersGet.ts
- packages/common/src/templatization.ts
- packages/common/test/mocks/templates.ts
- packages/common/test/mocks/utils.ts
- packages/common/test/restHelpers.test.ts
- packages/common/test/templatization.test.ts
- packages/creator/test/createSolutionItem.test.ts
- packages/deployer/src/deployer.ts
- packages/deployer/test/deployer.test.ts
- packages/feature-layer/test/feature-layer.test.ts
- packages/simple-types/test/webmappingapplication.test.ts
> store portal response as organization and store current user info

- packages/common/src/templatization.ts
- packages/common/test/mocks/templates.ts
- packages/common/test/mocks/utils.ts
- packages/common/test/restHelpers.test.ts
- packages/common/test/templatization.test.ts
- packages/creator/test/createSolutionItem.test.ts
- packages/deployer/src/deployer.ts
- packages/deployer/test/deployer.test.ts
- packages/simple-types/test/simple-types.test.ts
- packages/simple-types/test/webmap.test.ts
- packages/simple-types/test/webmappingapplication.test.ts
- packages/storymap/test/storymap.test.ts
> portal url work

- packages/simple-types/src/simple-types.ts
> set appItemId manually

- packages/common/src/resourceHelpers.ts
- packages/common/src/templatization.ts
- packages/common/test/resourceHelpers.test.ts
- packages/creator/test/creator.test.ts
- packages/deployer/test/deploySolutionItems.test.ts
- packages/group/src/group.ts
- packages/group/test/group.test.ts
- packages/simple-types/src/simple-types.ts
- packages/storymap/test/storymap.test.ts
> handle group resources

- package-lock.json
- package.json
- packages/common/examples/convertExtent/package-lock.json
- packages/common/examples/copyItemInfo/package-lock.json
- packages/common/examples/copySolutions/package-lock.json
- packages/common/examples/getItemInfo/package-lock.json
- packages/common/package-lock.json
- packages/common/package.json
- packages/creator/examples/createSolutionFromGroup/package-lock.json
- packages/creator/examples/createSolutionFromItem/package-lock.json
- packages/creator/package-lock.json
- packages/deployer/package-lock.json
- packages/feature-layer/package-lock.json
- packages/file/package-lock.json
- packages/group/package-lock.json
- packages/simple-types/package-lock.json
- packages/storymap/package-lock.json
- packages/viewer/package-lock.json
> Upped adlib version, moved @types/adlib to package that uses it, & updated package-locks

- packages/creator/src/createItemTemplate.ts
- packages/deployer/src/deploySolutionItems.ts
- packages/simple-types/src/simple-types.ts
- packages/simple-types/test/simple-types.test.ts
- packages/storymap/test/storymap.test.ts
Basically only templatize the item id while retaining everything else.
#56
> handle "Getting to know" type apps

- packages/deployer/src/deployer.ts
- packages/deployer/test/deployer.test.ts
- packages/simple-types/src/webmappingapplication.ts
- packages/simple-types/test/simple-types.test.ts
- packages/simple-types/test/webmappingapplication.test.ts
> reduce deployed size

- packages/common/src/generalHelpers.ts
- packages/common/src/interfaces.ts
- packages/common/src/templatization.ts
- packages/common/test/featureServiceHelpers.test.ts
- packages/common/test/generalHelpers.test.ts
- packages/common/test/mocks/templates.ts
- packages/common/test/restHelpers.test.ts
- packages/common/test/templatization.test.ts
- packages/creator/src/createItemTemplate.ts
- packages/creator/src/creator.ts
- packages/creator/test/createItemTemplate.test.ts
- packages/creator/test/creator.test.ts
- packages/deployer/src/deploySolutionItems.ts
- packages/deployer/src/deployer.ts
- packages/deployer/test/deploySolutionItems.test.ts
- packages/deployer/test/deployer.test.ts
- packages/group/src/group.ts
- packages/group/test/group.test.ts
- packages/simple-types/src/simple-types.ts
- packages/simple-types/src/workforce.ts
- packages/simple-types/test/simple-types.test.ts
- packages/simple-types/test/webmap.test.ts
- packages/simple-types/test/webmappingapplication.test.ts
- packages/simple-types/test/workforce.test.ts
> Circular dependencies take 2

- packages/deployer/src/deployer.ts
- packages/deployer/test/deployer.test.ts
> user defined params

- packages/common/test/mocks/templates.ts
- packages/simple-types/src/workforce.ts
- packages/simple-types/test/simple-types.test.ts
That test seems redundant.
What would you think about this...
> remove redundant test

- package-lock.json
- packages/common/examples/convertExtent/package-lock.json
- packages/common/examples/copyItemInfo/package-lock.json
- packages/common/examples/copySolutions/package-lock.json
- packages/common/examples/getItemInfo/package-lock.json
- packages/common/src/generalHelpers.ts
- packages/common/src/restHelpers.ts
- packages/common/src/templatization.ts
- packages/common/test/generalHelpers.test.ts
- packages/common/test/restHelpers.test.ts
- packages/common/test/templatization.test.ts
- packages/creator/examples/createSolutionFromGroup/package-lock.json
- packages/creator/examples/createSolutionFromItem/package-lock.json
- packages/creator/package-lock.json
- packages/creator/src/createItemTemplate.ts
- packages/deployer/examples/deploySolution/package-lock.json
- packages/deployer/package-lock.json
- packages/deployer/src/deploySolutionItems.ts
- packages/feature-layer/package-lock.json
- packages/file/package-lock.json
- packages/group/package-lock.json
- packages/simple-types/package-lock.json
- packages/simple-types/src/simple-types.ts
- packages/simple-types/src/webmappingapplication.ts
- packages/storymap/package-lock.json
> Restored relationships from deployed simple-types items

- packages/creator/src/createItemTemplate.ts
- packages/deployer/examples/implementedTypes/index.html
- packages/deployer/examples/implementedTypes/lerna.json
- packages/deployer/examples/implementedTypes/lib/contents.md
- packages/deployer/examples/implementedTypes/package-lock.json
- packages/deployer/examples/implementedTypes/package.json
- packages/deployer/examples/implementedTypes/src/main.ts
- packages/deployer/examples/implementedTypes/tsconfig.json
- packages/deployer/examples/implementedTypes/tslib.js
- packages/deployer/src/deploySolutionItems.ts
Simple example app to help solution developers know what might be expected to work
> Report implemented AGO item types

- packages/common/src/interfaces.ts
- packages/common/src/templatization.ts
- packages/common/test/mocks/templates.ts
- packages/simple-types/test/simple-types.test.ts
> Persist "properties" property

- packages/deployer/src/deployer.ts
- packages/deployer/test/deployer.test.ts
> update final solution item

- packages/simple-types/src/webmap.ts
- packages/simple-types/src/workforce.ts
- packages/simple-types/test/webmap.test.ts
- packages/simple-types/test/workforce.test.ts
> update webmap layer itemId logic

- packages/common/examples/copySolutions/src/main.ts
> Added properties to copy in copySolutions example

- packages/common/src/interfaces.ts
- packages/common/src/lib.ts
- packages/common/src/templatization.ts
- packages/common/test/lib.test.ts
- packages/common/test/mocks/utils.ts
- packages/common/test/resourceHelpers.test.ts
- packages/creator/src/creator.ts
- packages/creator/test/creator.test.ts
- packages/deployer/src/deploySolutionItems.ts
- packages/deployer/src/deployer.ts
- packages/deployer/test/deploySolutionItems.test.ts
- packages/deployer/test/deployer.test.ts
> Added job id

- package-lock.json
- packages/common/examples/convertExtent/package-lock.json
- packages/common/examples/copyItemInfo/package-lock.json
- packages/common/examples/copySolutions/package-lock.json
- packages/common/examples/getItemInfo/package-lock.json
- packages/common/package-lock.json
- packages/common/src/lib.ts
- packages/common/src/restHelpers.ts
- packages/creator/examples/createSolution/package-lock.json
- packages/deployer/examples/deploySolution/package-lock.json
- packages/deployer/examples/implementedTypes/package-lock.json
- packages/deployer/src/deployer.ts
> Support concurrent deployments

- package.json
- packages/common/src/interfaces.ts
- packages/common/src/restHelpers.ts
- packages/common/test/featureServiceHelpers.test.ts
- packages/common/test/restHelpers.test.ts
- packages/deployer/src/deploySolutionItems.ts
- packages/deployer/test/deploySolutionItems.test.ts
- packages/deployer/test/deployer.test.ts
- packages/simple-types/src/simple-types.ts
- packages/simple-types/test/dashboard.test.ts
- packages/simple-types/test/simple-types.test.ts
> Added group contents search with categories et al.

- packages/common/src/generalHelpers.ts
- packages/common/src/resourceHelpers.ts
- packages/common/src/restHelpers.ts
- packages/common/test/resourceHelpers.test.ts
- packages/creator/src/createItemTemplate.ts
- packages/creator/test/createItemTemplate.test.ts
- packages/creator/test/creator.test.ts
- packages/deployer/test/deploySolutionItems.test.ts
- packages/deployer/test/deployer.test.ts
- packages/simple-types/test/simple-types.test.ts
> Use higher-res thumbnails

- packages/common/examples/convertExtent/index.html
- packages/common/examples/convertExtent/package.json
- packages/common/examples/copyItemInfo/index.html
- packages/common/examples/copyItemInfo/package.json
- packages/common/examples/copySolutions/index.html
- packages/common/examples/copySolutions/package.json
- packages/common/examples/getItemInfo/index.html
- packages/common/examples/getItemInfo/package.json
- packages/common/src/featureServiceHelpers.ts
- packages/common/src/resourceHelpers.ts
- packages/common/test/featureServiceHelpers.test.ts
- packages/creator/examples/createSolution/index.html
- packages/creator/examples/createSolution/package.json
- packages/deployer/examples/deploySolution/index.html
- packages/deployer/examples/deploySolution/package.json
- packages/deployer/examples/implementedTypes/index.html
- packages/deployer/examples/implementedTypes/package.json
- packages/feature-layer/src/feature-layer.ts
> Updated arcgis-rest-js to v2.10.0

- packages/common/src/featureServiceHelpers.ts
- packages/common/test/featureServiceHelpers.test.ts
> update field checking

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- packages/common/src/restHelpers.ts
- packages/common/test/restHelpers.test.ts
> Further effort to get around AGO update URL problem

- package-lock.json
- packages/common/package-lock.json
- packages/common/src/interfaces.ts
- packages/deployer/src/deploySolutionItems.ts
- packages/deployer/test/deploySolutionItems.test.ts
- packages/feature-layer/src/feature-layer.ts
- packages/file/src/file.ts
- packages/group/src/group.ts
- packages/simple-types/src/simple-types.ts
> Fix handling of already-deployed items when unrolling a deployment

- docs/Publishing to npmjs.md
- package-lock.json
- packages/common/examples/README.md
- packages/common/examples/sanitizeGroupItems/index.html
- packages/common/examples/sanitizeGroupItems/lib/contents.md
- packages/common/examples/sanitizeGroupItems/src/main.ts
- packages/common/examples/sanitizeGroupItems/tsconfig.json
- packages/common/examples/sanitizeGroupItems/tslib.js
- packages/common/package-lock.json
- packages/common/package.json
- packages/common/src/index.ts
- packages/common/src/libs.ts
- packages/common/test/libs.test.ts
- packages/creator/package-lock.json
- packages/deployer/package-lock.json
- packages/feature-layer/package-lock.json
- packages/file/package-lock.json
- packages/group/package-lock.json
- packages/simple-types/package-lock.json
- packages/storymap/package-lock.json
- packages/viewer/package-lock.json
and interface to arcgis-html-sanitizer
#245
> Added sanitizeGroupItems example

- packages/simple-types/src/webmappingapplication.ts
- packages/simple-types/test/webmappingapplication.test.ts
> update templatize layer url for web applications logic

- packages/common/examples/getGUID/index.html
- packages/common/examples/sanitizeGroupItems/index.html
- packages/creator/examples/createSolution/index.html
- packages/deployer/examples/deploySolution/index.html
- packages/deployer/examples/deploySolution/src/main.ts
- packages/deployer/examples/implementedTypes/index.html
- packages/deployer/src/deployer.ts
- packages/deployer/test/deployer.test.ts
> Preserved deployment options and updated example to exercise #240

- packages/common/src/interfaces.ts
- packages/common/src/restHelpers.ts
- packages/common/test/mocks/utils.ts
- packages/common/test/restHelpers.test.ts
- packages/group/src/group.ts
> Handle concurrent group creation

- packages/common/src/featureServiceHelpers.ts
- packages/common/src/generalHelpers.ts
- packages/common/src/resourceHelpers.ts
- packages/common/src/restHelpers.ts
- packages/common/src/restHelpersGet.ts
- packages/common/test/featureServiceHelpers.test.ts
- packages/common/test/generalHelpers.test.ts
- packages/deployer/test/deployer.test.ts
- packages/feature-layer/src/feature-layer.ts
- packages/simple-types/src/webmap.ts
- packages/simple-types/src/webmappingapplication.ts
> slash issue

- README.md
- packages/common/src/restHelpers.ts
- packages/deployer/src/deployer.ts
- packages/deployer/test/deployer.test.ts
> Copy metadata from solution template to deployed solution

- karma.conf.js
- packages/common/src/featureServiceHelpers.ts
- packages/common/src/restHelpers.ts
- packages/common/test/featureServiceHelpers.test.ts
- packages/common/test/mocks/agolItems.ts
- packages/common/test/mocks/templates.ts
- packages/common/test/restHelpers.test.ts
- packages/feature-layer/test/feature-layer.test.ts
> Support Cache Control property on Feature Services and Views

- docs/Publishing to npmjs.md
- package-lock.json
- packages/common/examples/copySolutions/index.html
- packages/common/examples/copySolutions/src/main.ts
- packages/common/package-lock.json
- packages/common/src/restHelpers.ts
- packages/common/test/restHelpers.test.ts
- packages/creator/package-lock.json
- packages/deployer/package-lock.json
- packages/deployer/src/deploySolutionItems.ts
- packages/deployer/src/deployer.ts
- packages/deployer/test/deploySolutionItems.test.ts
- packages/feature-layer/package-lock.json
- packages/file/package-lock.json
- packages/group/package-lock.json
- packages/simple-types/package-lock.json
- packages/storymap/package-lock.json
- packages/viewer/package-lock.json
> Make sure that the token used in a thumbnail's query param is fresh

- packages/common/src/interfaces.ts
- packages/common/src/restHelpers.ts
- packages/common/test/mocks/utils.ts
- packages/common/test/restHelpers.test.ts
- packages/deployer/examples/deploySolution/index.html
- packages/deployer/src/deploySolutionItems.ts
- packages/feature-layer/src/feature-layer.ts
- packages/file/src/file.ts
- packages/group/src/group.ts
- packages/simple-types/src/simple-types.ts
#310 
@cosbyr, will this work for you?
> Added progress event

- packages/common/src/interfaces.ts
- packages/creator/src/creator.ts
- packages/creator/test/creator.test.ts
- packages/deployer/test/deployerUtils.test.ts
> Moved solution id and version from properties to typekeywords

- packages/common/src/generalHelpers.ts
- packages/common/src/resourceHelpers.ts
- packages/common/test/resourceHelpers.test.ts
- packages/deployer/src/deployer.ts
- packages/simple-types/src/simple-types.ts
- packages/simple-types/test/simple-types.test.ts
> Restrict scanning to item base info

- README.md
This is an **awesome** library, I didn't quite get it until I watched the (similarly good) Dev Summit session. For others discovering this library and why it exists, I think it'd be helpful to call out the session at the top of the README (following the `rest-js` style).
> Update README.md with DevSummit session

- packages/common/examples/copySolutions/index.html
- packages/common/examples/copySolutions/src/main.ts
- packages/common/examples/getItemInfo/index.html
Default is to display just the user's solutions to reduce clutter, but sometimes one needs to access someone else's solutions.
Also added portal specification to getItemInfo so that portals other than www.arcgis.com can be used.
> Added org switch to copySolutions example

- packages/common/src/restHelpers.ts
- packages/common/test/restHelpers.test.ts
- packages/deployer/src/deploySolutionFromTemplate.ts
Some autoformatting happened there when I comitted.
@chris-fox @MikeTschudi I used this as the default:
extent.xmin = -179;
extent.xmax = 179;
extent.ymax = 89;
extent.ymin = -89;
extent.spatialReference = { wkid: 4326 }
If I used the 180/90 project would return NaN values. If you know of a more suitable default please let me know.
> extent failover

- .gitignore
- package.json
- packages/common/package.json
- packages/creator/package.json
- packages/deployer/package.json
- packages/feature-layer/package.json
- packages/file/package.json
- packages/group/package.json
- packages/hub-types/package-lock.json
- packages/hub-types/package.json
- packages/simple-types/package.json
- packages/storymap/package.json
- packages/viewer/package.json
As it says. This will ensure that local and ci/build systems all use the 3.9.2 version of typescript
> Update Typescript Version in all Packages

- amd-requirejs-dojo.html
- docs/acetate.config.js
- docs/build-typedoc.js
- docs/generate-srihashes.js
- docs/src/guides/amd-requirejs-dojo.md
- docs/src/guides/browser-authentication.md
- docs/src/guides/client-server-authentication.md
- docs/src/guides/from-a-cdn.md
- docs/src/guides/index.md
- docs/src/guides/node.md
- docs/src/guides/package-overview.md
- docs/src/guides/server-authentication.md
- from-a-cdn.html
- packages/common/README.md
> Fixed various doc errors

- .gitignore
- demos/deploySolution/index.html
- demos/deploySolution/package-lock.json
- demos/deploySolution/package.json
- package-lock.json
- package.json
- packages/common/package-lock.json
- packages/common/package.json
- packages/deployer/package-lock.json
- packages/deployer/package.json
- packages/hub-types/package-lock.json
- packages/hub-types/package.json
- packages/hub-types/src/helpers/create-hub-request-options.ts
- packages/hub-types/src/helpers/move-site-to-folder.ts
- packages/hub-types/src/hub-site-processor.ts
- packages/hub-types/src/index.ts
- packages/hub-types/test/helpers/create-hub-request-options.test.ts
- packages/hub-types/test/helpers/move-site-to-folder.test.ts
This lands the initial support for creating a site (and it's teams + initiative based on licensing).
It has only been tested using a Solution item created by the Hub application.
Note: this is not ready to ship
Known Issues:
- need to implement postProcessing step, whcih will need some changed to deployer flow
- need to resolve differences in how resources/assets are handled
- need to handle "rolling back" if/when the solution deploy fails
- I expect others
> Create Site using Hub Solution Item

- packages/storymap/package-lock.json
- packages/storymap/package.json
- packages/storymap/src/storymap.ts
Unnecessary and interfering with build process
> Removed circular dependency between simple-types and storymap packages

- packages/deployer/src/deploySolutionFromTemplate.ts
> dependency IDs were no longer being updated

- packages/common/src/featureServiceHelpers.ts
- packages/feature-layer/test/feature-layer.test.ts
#384
PR looks bigger than it is. The only real change is to avoid using the admin api for getting the basic info for living atlas layers.
> living atlas

- package-lock.json
- package.json
- packages/common/src/templatization.ts
- packages/common/test/templatization.test.ts
> add fallback for getDefaultLocatorURL

- packages/common/src/generalHelpers.ts
- packages/common/src/templatization.ts
- packages/creator/src/creator.ts
- packages/creator/test/creator.test.ts
> Returned solutionid to a 32-char string

- packages/common/src/templatization.ts
- packages/common/test/templatization.test.ts
- packages/simple-types/test/simple-types.test.ts
> conditional extent

- demos/copySolutions/index.html
- demos/copySolutions/src/main.ts
- demos/getItemInfo/index.html
And changed getItemInfo UI portal to not include "/sharing/rest"
> Enabled copySolutions to fetch more than 100 Solutions

- packages/common/src/restHelpers.ts
> remove adminServiceInfo for portal deployment

- packages/simple-types/src/workforce.ts
> remove the lookbehind and just look for FS url

- demos/addResource/package-lock.json
- demos/compareJSON/package-lock.json
- demos/convertExtent/package-lock.json
- demos/copyItemInfo/package-lock.json
- demos/copySolutions/package-lock.json
- demos/createFolder/package-lock.json
- demos/createSolution/package-lock.json
- demos/deploySolution/package-lock.json
- demos/getGUID/package-lock.json
- demos/getGroupInfo/package-lock.json
- demos/getItemInfo/package-lock.json
- demos/getSolutions/package-lock.json
- demos/implementedTypes/package-lock.json
- demos/polyfillExplorer/package-lock.json
- demos/sanitizeGroupItems/package-lock.json
- demos/sanitizer/package-lock.json
- demos/searchGroupCategories/package-lock.json
- package-lock.json
- packages/deployer/src/deploySolutionFromTemplate.ts
- packages/deployer/test/deploySolutionFromTemplate.test.ts
> Fix construction of Enterprise portal base url

- packages/common/src/resourceHelpers.ts
- packages/common/src/restHelpers.ts
- packages/common/test/resourceHelpers.test.ts
- packages/common/test/restHelpers.test.ts
- packages/deployer/src/deploySolutionItems.ts
- packages/deployer/test/deploySolutionFromTemplate.test.ts
- packages/deployer/test/deployer.test.ts
> Include an item's folder when updating it with a zip file 

- packages/common/src/restHelpers.ts
- packages/common/test/restHelpers.test.ts
This is to address an issue Chris noticed with a failure to project the orgs default extent and default world extent to the user defined spatial reference.
> update how we handle fallback extent

- packages/deployer/src/deployer.ts
> Update authentication for fetching item template

- packages/common/src/generalHelpers.ts
- packages/common/src/workforceHelpers.ts
- packages/common/test/generalHelpers.test.ts
- packages/common/test/workforceHelpers.test.ts
- packages/creator/src/helpers/add-content-to-solution.ts
- packages/creator/test/helpers/add-content-to-solution.test.ts
> And end ofSolution creation, templatize all references to items in Solution

- packages/common/src/generalHelpers.ts
- packages/common/test/generalHelpers.test.ts
- packages/creator/src/helpers/add-content-to-solution.ts
- packages/creator/test/creator.test.ts
#477 
and reverted templatizing ids in the `assets` property done in PR #493
> Templatize org URLs in an object

- packages/common/src/dependencies.ts
- packages/common/src/featureServiceHelpers.ts
- packages/common/test/featureServiceHelpers.test.ts
- packages/deployer/src/deploySolutionItems.ts
- packages/deployer/test/deploySolutionItems.test.ts
> 8 4 issues

- packages/common/package-lock.json
- packages/common/package.json
- packages/common/src/featureServiceHelpers.ts
- packages/creator/package-lock.json
- packages/creator/package.json
- packages/deployer/package-lock.json
- packages/deployer/package.json
- packages/feature-layer/package-lock.json
- packages/feature-layer/package.json
- packages/file/package-lock.json
- packages/file/package.json
- packages/form/package-lock.json
- packages/form/package.json
- packages/group/package-lock.json
- packages/group/package.json
- packages/hub-types/package-lock.json
- packages/hub-types/package.json
- packages/simple-types/package-lock.json
- packages/simple-types/package.json
- packages/storymap/package-lock.json
- packages/storymap/package.json
- packages/viewer/package-lock.json
- packages/viewer/package.json
- packages/web-experience/package-lock.json
- packages/web-experience/package.json
[comment](https://github.com/Esri/solution.js/issues/477#issuecomment-708560974) in #477
> Save the urls in the feature layer's `properties` area

- demos/src/deploy-solution-main.ts
> Removed overrides for solution details in deploy solution demo app

- packages/creator/src/createItemTemplate.ts
> Save item urls in templateDictionary

- demos/package-lock.json
- package-lock.json
- packages/common/package-lock.json
- packages/common/package.json
- packages/common/test/mocks/utils.ts
- packages/creator/package-lock.json
- packages/creator/package.json
- packages/deployer/package-lock.json
- packages/deployer/package.json
- packages/deployer/src/deploySolutionFromTemplate.ts
- packages/deployer/src/deploySolutionItems.ts
- packages/feature-layer/package-lock.json
- packages/feature-layer/package.json
- packages/file/package-lock.json
- packages/file/package.json
- packages/form/package-lock.json
- packages/form/package.json
- packages/group/package-lock.json
- packages/group/package.json
- packages/hub-types/package-lock.json
- packages/hub-types/package.json
- packages/simple-types/package-lock.json
- packages/simple-types/package.json
- packages/storymap/package-lock.json
- packages/storymap/package.json
- packages/viewer/package-lock.json
- packages/viewer/package.json
- packages/web-experience/package-lock.json
- packages/web-experience/package.json
> Filtered groups list to only keep user-owned groups (vs. user-belonging-to-groups)

- packages/common/src/featureServiceHelpers.ts
- packages/common/test/featureServiceHelpers.test.ts
> update geom field logic

- packages/common/src/interfaces.ts
- packages/form/src/helpers/build-create-params.ts
- packages/form/src/helpers/post-process-survey.ts
- packages/form/test/helpers/build-create-params.test.ts
- packages/form/test/helpers/create-item-from-hub-template.test.ts
- packages/form/test/helpers/post-process-survey.test.ts
[157788](https://esriarlington.tpondemand.com/entity/157788-ghpublisher2-cant-activate-template-containing-survey)
Removes `thumbnailFile` param from Survey123 call
> 157788 - Remove thumbnailFile from survey123 API call

- demos/copyItemInfo/index.html
- demos/copySolutions/index.html
- demos/deploySolution/index.html
- demos/src/deploy-solution-main.ts
https://github.com/Esri/solution.js/issues/431#issuecomment-716651573
Also
* updated JSAPI version in copyItemInfo and copySolutions demos
* changed copySolutions demo to have defaults for portals (i.e., derived from credentials) rather than hints that have to be entered
> Add option to provide source credentials in deploySolution

- packages/creator/src/creator.ts
- packages/creator/test/creator.test.ts
- packages/deployer/src/deploySolutionFromTemplate.ts
- packages/deployer/test/deploySolutionFromTemplate.test.ts
- packages/deployer/test/deployer.test.ts
see https://github.com/Esri/solution.js/issues/488#issuecomment-724784318
> Request larger-size thumbnails from sources

- packages/common/src/restHelpers.ts
Patches arcgis-rest-js' `request` function until PR 777 in that repo gets merged.
> Added patch for group category search

- packages/creator/src/module-map.ts
- packages/deployer/src/module-map.ts
- packages/simple-types/src/helpers/convert-item-to-template.ts
> Add support for feature collection

- packages/common/src/resourceHelpers.ts
- packages/simple-types/test/helpers/convert-item-to-template.test.ts
> Handle surveys with zip files named undefined

- packages/creator/src/module-map.ts
- packages/deployer/src/module-map.ts
- packages/simple-types/src/helpers/convert-item-to-template.ts
> Add support for Insights Model

- packages/creator/src/helpers/add-content-to-solution.ts
- packages/creator/test/helpers/add-content-to-solution.test.ts
> Handle missing description

- packages/common/src/featureServiceHelpers.ts
> chunk add to def calls

- packages/common/src/restHelpers.ts
- packages/common/test/restHelpers.test.ts
> update for index isUnique logic

- packages/common/src/featureServiceHelpers.ts
- packages/common/test/featureServiceHelpers.test.ts
> update type keywords

- packages/deployer/src/helpers/post-process.ts
- packages/group/src/group.ts
See https://github.com/Esri/solution.js/issues/575#issuecomment-780059839 and following
Also fixed deploySolution's status messages for groups to report the source group
> Filter out groups from setting up a relationship between a deployed Solution and its fellow deployees.

- demos/copySolutions/index.html
In addition to list of solutions in source organization, an option is provided to enter the id of a solution item:
> Added option to enter solution id in copySolutions

- packages/deployer/test/deploySolutionItems.test.ts
- packages/feature-layer/src/feature-layer.ts
- packages/feature-layer/test/feature-layer.test.ts
> Insure that feature layer urls end with /

- demos/deleteSolution/index.html
- demos/index.html
- demos/package-lock.json
- demos/src/delete-solution-main.ts
- packages/common/src/deleteSolution.ts
- packages/common/src/index.ts
- packages/common/src/interfaces.ts
- packages/common/src/templatization.ts
- packages/common/test/deleteSolution.test.ts
- packages/common/test/mocks/agolItems.ts
- packages/common/test/templatization.test.ts
- packages/viewer/test/viewer.test.ts
but only if the deployed Solution item is a version "1" deployment, i.e., one that has its items listed in build order
> Delete deployed Solution items and the items deployed with them

- packages/common/src/deleteSolution.ts
- packages/common/test/deleteSolution.test.ts
These are deployed Solution items before the `version` property was added to the `metadata` section
> Delete version 0 deployed Solution items and the items deployed with them

- packages/common/src/restHelpers.ts
- packages/common/test/restHelpers.test.ts
@MikeTschudi I've had mixed results adding the async=true on devext. In prod we do start to see the size error that would be expected. On dev it has worked occasionally. Yesterday it was consistently causing failures in the morning but then appeared to be working in the afternoon. This morning it appears to be causing failures again. I'm not exactly sure what to make of it but have added for add/update/delete
> retry add update calls

- packages/common/src/restHelpers.ts
- packages/common/test/restHelpers.test.ts
Cherry-picked from #640 to patch 9.1
> retry add update calls as 9.1 patch

- packages/common/src/workforceHelpers.ts
- packages/common/test/workforceHelpers.test.ts
> workforce deploy

- packages/simple-types/src/webmap.ts
> remove intialState

- demos/deleteSolution/index.html
- packages/common/src/deleteHelpers/deleteEmptyGroups.ts
- packages/common/src/deleteHelpers/deleteGroupIfEmpty.ts
- packages/common/src/deleteHelpers/deleteSolutionFolder.ts
- packages/common/src/deleteHelpers/index.ts
- packages/common/src/deleteHelpers/reconstructBuildOrderIds.ts
- packages/common/src/deleteHelpers/removeItems.ts
- packages/common/src/deleteHelpers/reportProgress.ts
- packages/common/src/deleteSolution.ts
- packages/common/src/getSolutionSummary.ts
- packages/common/src/interfaces.ts
- packages/common/test/deleteSolution.test.ts
- packages/common/test/mocks/agolItems.ts
- packages/common/test/mocks/utils.ts
Deletes Solution groups iff they are empty and the calling user owns the group; see https://github.com/Esri/solution.js/issues/624#issuecomment-847183249
> Delete Solution groups when deleting Solutions

- packages/common/src/deleteHelpers/deleteSolutionItem.ts
- packages/common/src/deleteHelpers/index.ts
- packages/common/src/deleteSolution.ts
- packages/common/test/deleteSolution.test.ts
- packages/creator/src/creator.ts
- packages/deployer/src/deploySolutionFromTemplate.ts
- packages/deployer/test/deploySolutionFromTemplate.test.ts
- packages/deployer/test/deployer.test.ts
#657, as well as unprotect it when deleting a deployed Solution (#624)
> Delete-protect deployed Solution item

- README.md
- packages/common/src/resources/store-item-resources.ts
- packages/common/test/resources/store-item-resources.test.ts
Fixes #660, in which the ExB draft file was being kept when creating a Solution.
> Restore removing ExB config.json file

- demos/getItemInfo/index.html
- demos/package.json
- demos/src/getFormattedItemInfo.ts
- packages/common/src/getItemTypeAbbrev.ts
- packages/common/src/index.ts
- packages/common/test/mocks/agolItems.ts
- packages/common/test/mocks/templates.ts
- packages/creator/src/helpers/add-content-to-solution.ts
- packages/deployer/test/helpers/sortTemplates.test.ts
- packages/file/src/file.ts
- packages/group/src/group.ts
- packages/hub-types/src/hub-page-processor.ts
- packages/hub-types/src/hub-site-processor.ts
- packages/simple-types/src/helpers/convert-item-to-template.ts
- packages/simple-types/src/notebook.ts
- packages/simple-types/src/quickcapture.ts
- packages/simple-types/src/simple-types.ts
- packages/simple-types/src/webmappingapplication.ts
#652 
Also
* restored solution dependency graph display in demo getItemInfo
* added function documentation
> Don't add dependencies during post-processing

- packages/deployer/src/deploySolutionFromTemplate.ts
- packages/deployer/test/deployer.test.ts
See https://github.com/Esri/solution.js/issues/657#issuecomment-866175274
> Unprotect and then delete solution upon failure

- demos/createSolution/index.html
- demos/src/create-solution-main.ts
- packages/creator/src/createItemTemplate.ts
- packages/creator/src/creator.ts
- packages/creator/src/helpers/add-content-to-solution.ts
- packages/creator/test/creator.test.ts
- packages/creator/test/helpers/add-content-to-solution.test.ts
...so that one can use a non-public source item or group
> Add source credentials to create solution

- CHANGELOG.md
- demos/createSolution/index.html
- demos/src/create-solution-main.ts
- packages/common/src/interfaces.ts
- packages/common/src/resourceHelpers.ts
- packages/common/src/resources/copyAssociatedFiles.ts
- packages/common/src/resources/getItemResourcesPaths.ts
- packages/common/src/resources/index.ts
- packages/common/test/resources/copyAssociatedFiles.test.ts
- packages/common/test/resources/getItemResourcesPaths.test.ts
- packages/creator/src/createItemTemplate.ts
- packages/creator/src/creator.ts
- packages/creator/src/helpers/add-content-to-solution.ts
- packages/creator/test/createItemTemplate.test.ts
- packages/creator/test/creator.test.ts
- packages/creator/test/helpers/add-content-to-solution.test.ts
> Bundle resource sending to created Solution item

- CHANGELOG.md
- packages/common/src/getItemTypeAbbrev.ts
- packages/common/test/resources/store-item-resources.test.ts
- packages/creator/src/module-map.ts
- packages/deployer/src/module-map.ts
- packages/simple-types/src/helpers/convert-item-to-template.ts
> Added support for Web Scene item type

- packages/creator/src/helpers/add-content-to-solution.ts
> Don't templatize Living Atlas item ids

- packages/common/src/interfaces.ts
- packages/common/src/resourceHelpers.ts
- packages/common/src/resources/getItemResourcesFilesFromPaths.ts
- packages/common/test/resourceHelpers.test.ts
- packages/common/test/resources/copyAssociatedFiles.test.ts
- packages/common/test/resources/getItemResourcesPaths.test.ts
- packages/creator/src/helpers/add-content-to-solution.ts
> Prune resources of non-existent items from Solution

- packages/common/src/resources/copyAssociatedFiles.ts
- packages/common/test/resources/copyAssociatedFiles.test.ts
When there are more than 40 resources to be sent to a created Solution item, the resources are divided into multiple zip files.  Since AGO has a problem with many zips sent to the same item at roughly the same time, we insert a one-second delay between sending each zip.
See comment https://github.com/Esri/solution.js/issues/679#issuecomment-878396297
> Send zips to Solution item with delays between sends

- demos/deleteSolution/index.html
- demos/deploySolution/index.html
Error handler wasn't calling function correctly; see https://github.com/Esri/solution.js/pull/694#discussion_r677555283
> Fixed deleteSolution error handling

- demos/deploySolution/index.html
- demos/src/deploy-solution-main.ts
Allows us to pass custom params like wkid or the upcoming feature service id.
> add custom params to deploy demo

- packages/common/src/featureServiceHelpers.ts
- packages/common/test/featureServiceHelpers.test.ts
> add default sr when missing

- packages/deployer/src/deploySolutionItems.ts
- packages/deployer/test/deploySolutionItems.test.ts
> add type keyword

- packages/common/src/featureServiceHelpers.ts
- packages/common/test/featureServiceHelpers.test.ts
- packages/deployer/src/deploySolutionItems.ts
- packages/deployer/test/deploySolutionItems.test.ts
> remove sourceId and use enterpriseIDMapping

- packages/common/src/interfaces.ts
- packages/common/src/resources/get-blob.ts
- packages/common/src/restHelpersGet.ts
- packages/common/test/restHelpersGet.test.ts
...without treating it as an AGO item or data or anything else.
> Add a function to simply get JSON

- packages/common/src/featureServiceHelpers.ts
- packages/common/src/restHelpers.ts
- packages/common/test/restHelpers.test.ts
> add relationships for views after layers when layer chunking is used

- packages/common/src/featureServiceHelpers.ts
- packages/common/src/restHelpers.ts
- packages/common/test/restHelpers.test.ts
> Relationship chunking

- packages/common/src/interfaces.ts
- packages/velocity/src/helpers/velocity-helpers.ts
- packages/velocity/test/helpers/velocity-helpers.test.ts
> add error checks

- packages/simple-types/src/oic.ts
- packages/simple-types/test/oic.test.ts
> add portal base url var and templatize the id

- packages/common/src/migrations/upgrade-two-dot-five.ts
- packages/common/test/migrations/upgrade-two-dot-five.test.ts
- packages/form/src/helpers/build-create-params.ts
- packages/form/src/helpers/encode-survey-form.ts
- packages/form/test/helpers/build-create-params.test.ts
- packages/form/test/helpers/encode-survey-form.test.ts
Hub filed [bug 2474](https://devtopia.esri.com/dc/hub/issues/2474) which is related to supporting surveys containing "pages". This PR fixes the same in Solution.js
> Support paged surveys

- packages/viewer/src/viewer.ts
- packages/viewer/test/viewer.test.ts
Handle more variations of cycles in solution templates
#713
> Improved cycle handling when displaying a solution template

- docs/src/guides/package-overview.md
- packages/common/src/restHelpers.ts
- packages/common/src/restHelpersGet.ts
- packages/common/test/restHelpers.test.ts
- packages/common/test/restHelpersGet.test.ts
- packages/file/package.json
- packages/hub-types/package.json
- packages/hub-types/src/hub-page-processor.ts
- packages/hub-types/src/hub-site-processor.ts
- packages/hub-types/test/hub-page-processor.test.ts
- packages/hub-types/test/hub-site-processor.test.ts
> Fixed the package overview guide

- packages/simple-types/src/notebook.ts
- packages/simple-types/test/notebook.test.ts
> notebooks update

- packages/common/src/templatization.ts
- packages/common/test/mocks/agolItems.ts
- packages/creator/src/createItemTemplate.ts
- packages/deployer/src/deploySolutionFromTemplate.ts
- packages/deployer/src/deploySolutionItems.ts
- packages/deployer/test/deploySolutionItems.test.ts
- packages/group/src/group.ts
- packages/group/test/group.test.ts
- packages/simple-types/src/webmap.ts
- packages/simple-types/test/simple-types.test.ts
- packages/simple-types/test/webmap.test.ts
> check group typeKeywords for source references

- packages/deployer/src/deploySolutionFromTemplate.ts
- packages/deployer/test/deploySolutionFromTemplate.test.ts
#765
@MikeTschudi one spot I missed. Older group templates won't have the typeKeywords array.
> typeKeywords for older groups

- packages/common/src/restHelpers.ts
for solution deployment app issue https://github.com/ArcGIS/solution-deployment-app/issues/785
> update how auth is set

- demos/getPortalInfo/index.html
- demos/index.html
- demos/package-lock.json
- package-lock.json
- package.json
- packages/common/package-lock.json
- packages/common/src/generalHelpers.ts
- packages/common/test/generalHelpers.test.ts
- packages/common/test/restHelpers.test.ts
- packages/creator/package-lock.json
- packages/deployer/package-lock.json
- packages/deployer/test/deploySolutionFromTemplate.test.ts
- packages/deployer/test/deployer.test.ts
- packages/feature-layer/package-lock.json
- packages/file/package-lock.json
- packages/form/package-lock.json
- packages/group/package-lock.json
- packages/hub-types/package-lock.json
- packages/simple-types/package-lock.json
- packages/storymap/package-lock.json
- packages/velocity/package-lock.json
- packages/viewer/package-lock.json
- packages/web-experience/package-lock.json
* Added getPortalInfo demo to show self/ and self/settings/ info about a portal; query can be unauthenticated or authenticated
* Added demo folder to npm deepclean
* Merged GitHub dependabot package-lock.json update
* Updated package-lock.json files
* Added common function getPropWithDefault
* Add fetchMocks required by AGO changes
> Miscellaneous additions to support work in Solution deployment app

- packages/common/src/restHelpers.ts
- packages/common/test/mocks/utils.ts
- packages/common/test/restHelpers.test.ts
- packages/group/test/group.test.ts
* Added `common` function `searchGroupAllContents` to return all results from searching a group--not just the first 100
* Changed start of paging request from 0 to 1 to match AGO
> Add function searchGroupAllContent

- packages/common/src/restHelpers.ts
- packages/common/test/restHelpers.test.ts
- packages/group/src/group.ts
- packages/group/test/group.test.ts
> post process groups

- packages/common/src/restHelpers.ts
- packages/common/test/mocks/utils.ts
- packages/common/test/restHelpers.test.ts
to get all items matching a query, even beyond the AGO 100-item limit.
Also generalized getGroupSearchResponse test-result generator into getSearchResponse handling groups, items, users.
> Added function searchAllItems

- packages/feature-layer/src/feature-layer.ts
- packages/feature-layer/test/feature-layer.test.ts
#762
Latest of feature layer's modified date & the lastEditDate of each of its tables and layers.
> Update the feature layer's modified date to the latest date it contains

- packages/common/src/featureServiceHelpers.ts
- packages/common/test/featureServiceHelpers.test.ts
> always set isViewOverride

- demos/deploySolutionCustom/index.html
* Removed version display after it was moved into Solution titles
* Removed destination OAuth entry
> Updates to custom deploy solution demo

- packages/common/src/featureServiceHelpers.ts
- packages/common/test/featureServiceHelpers.test.ts
> Update for ms views

- packages/creator/src/createItemTemplate.ts
- packages/creator/test/creator.test.ts
> remove failed

- .github/workflows/lint.yml
whenever there's a push or pull request on `develop` or `master`
> Add GitHub action to do linting

- packages/common/src/featureServiceHelpers.ts
- packages/common/test/featureServiceHelpers.test.ts
> Remove size prop

- packages/common/src/interfaces.ts
- packages/deployer/src/deploySolutionItems.ts
- packages/deployer/test/deploySolutionItems.test.ts
> Find existing fix

- packages/common/src/featureServiceHelpers.ts
- packages/common/test/featureServiceHelpers.test.ts
> Fix is view override

- package-lock.json
> Update dependency engine.io

- build.bat
- build_dev.bat
- demos/compareJSON/package-lock.json
- demos/copyItemInfo/package-lock.json
- demos/copySolutions/package-lock.json
- demos/createSolution/package-lock.json
- demos/deleteSolution/package-lock.json
- demos/deploySolution/package-lock.json
- demos/getItemInfo/package-lock.json
- demos/verifySolution/package-lock.json
The build scripts weren't able to handle a fresh clone
> Fix build scripts

- demos/compareJSON/package-lock.json
- demos/copyItemInfo/package-lock.json
- demos/copySolutions/package-lock.json
- demos/createSolution/package-lock.json
- demos/deleteSolution/package-lock.json
- demos/deploySolution/package-lock.json
- demos/getItemInfo/package-lock.json
- demos/implementedTypes/package-lock.json
- demos/verifySolution/package-lock.json
- packages/creator/src/createItemTemplate.ts
- packages/creator/src/creator.ts
- packages/creator/test/createItemTemplate.test.ts
- packages/deployer/src/deploySolutionFromTemplate.ts
- packages/deployer/src/deployer.ts
- packages/simple-types/test/helpers/convert-item-to-template.test.ts
Also removed reporting result of sanitizing
#1151
> Fix handling of QuickCapture resources

- demos/compareJSON/package-lock.json
- demos/copyItemInfo/package-lock.json
- demos/copySolutions/package-lock.json
- demos/createSolution/package-lock.json
- demos/deleteSolution/package-lock.json
- demos/deploySolution/package-lock.json
- demos/getItemInfo/package-lock.json
- demos/implementedTypes/package-lock.json
- demos/verifySolution/package-lock.json
- packages/creator/src/createItemTemplate.ts
> Fix handling of resources for non-QC items

- packages/simple-types/src/webmap.ts
- packages/simple-types/test/webmap.test.ts
https://github.com/Esri/solution.js/issues/1255#issuecomment-1749340498
> Update handling of VectorTileLayers

- package-lock.json
- package.json
- packages/common/src/restHelpers.ts
- packages/common/test/restHelpers.test.ts
https://github.com/ArcGIS/solution-deployment-app/issues/995
> Remove the sortField if it's "relevance"

- packages/creator/src/helpers/add-content-to-solution.ts
- packages/storymap/src/helpers/create-storymap.ts
Templatize and de-templatized while preserving encoding
#1299
> Handle encoded portal URLs in StoryMaps

- package-lock.json
- package.json
- packages/common/src/resources/copyAssociatedFiles.ts
- packages/common/src/workforceHelpers.ts
- packages/hub-types/src/helpers/_post-process-site.ts
Handles changes necessary to support PR #1352
> Handle new eslint rules

- packages/creator/src/createItemTemplate.ts
- packages/deployer/src/deploySolutionItems.ts
- packages/deployer/src/helpers/zip-utils.ts
- packages/deployer/test/deploySolutionItems.test.ts
- packages/deployer/test/deployer.test.ts
- packages/deployer/test/helpers/zip-utils.test.ts
> Add support for Survey123 webhooks

- packages/common/src/workflowHelpers.ts
- packages/common/test/workflowHelpers.test.ts
Check to see if organization has the license to run Workflow Manager.
see https://developers.arcgis.com/workflow-manager/api-reference/rest/check-status/
> Added check for workflow permission

- packages/common/src/workflowHelpers.ts
- packages/common/test/workflowHelpers.test.ts
Check to see if organization has the license to run Workflow Manager.
> Fixed handling of checkStatus rejection

- packages/deployer/src/deploySolutionItems.ts
- packages/deployer/test/deploySolutionItems.test.ts
> Velocity issue

- packages/common/src/featureServiceHelpers.ts
- packages/common/src/interfaces.ts
- packages/common/test/featureServiceHelpers.test.ts
> Spatial reference issue

- packages/form/src/formUtils.ts
- packages/form/test/formUtils.test.ts
https://github.com/Esri/solution.js/issues/1418#issuecomment-1997396907
> Removed XLSX handling

- packages/creator/src/helpers/add-content-to-solution.ts
- packages/creator/test/helpers/add-content-to-solution.test.ts
- packages/workflow/src/workflow.ts
- packages/workflow/test/workflow.test.ts
[#875](https://github.com/Esri/solution.js/issues/875#issuecomment-2040764283)
> Refine workflow manager templatizing

- packages/creator/src/helpers/add-content-to-solution.ts
- packages/creator/test/helpers/add-content-to-solution.test.ts
> Fixed regression templatizing portal's URL

- demos/compareJSON/package-lock.json
- demos/compareSolutions/package-lock.json
- demos/copyItemInfo/package-lock.json
- demos/copySolutions/package-lock.json
- demos/createSolution/package-lock.json
- demos/deleteSolution/package-lock.json
- demos/deploySolution/package-lock.json
- demos/getItemInfo/package-lock.json
- demos/implementedTypes/package-lock.json
- demos/verifySolution/package-lock.json
- package-lock.json
- packages/common/src/zip-utils.ts
- packages/form/src/formUtils.ts
#1443
This is a patch to create v5.2.11 without incorporating the latest in the `develop` branch. Its contents will be merged into the `develop` branch in the future.
> Handle date oddity when S123 unzips its configuration

- demos/compareJSON/package-lock.json
- demos/compareSolutions/package-lock.json
- demos/copyItemInfo/package-lock.json
- demos/copySolutions/package-lock.json
- demos/createSolution/package-lock.json
- demos/deleteSolution/package-lock.json
- demos/deploySolution/authenticate.html
- demos/deploySolution/package-lock.json
- demos/deploySolution/package.json
- demos/deploySolution/src/authenticate.ts
- demos/deploySolution/webpack.config.js
- demos/getItemInfo/package-lock.json
- demos/implementedTypes/package-lock.json
- demos/verifySolution/package-lock.json
> Restored OAuth handling to deploySolution demo

- packages/common/src/completeItem.ts
- packages/common/src/interfaces.ts
- packages/common/src/restHelpers.ts
- packages/common/src/workflowHelpers.ts
- packages/common/test/completeItem.test.ts
- packages/common/test/deleteSolution.test.ts
- packages/common/test/restHelpers.test.ts
- packages/common/test/workflowHelpers.test.ts
- packages/deployer/src/deploySolutionFromTemplate.ts
- packages/deployer/src/deployer.ts
- packages/deployer/src/deployerUtils.ts
- packages/deployer/test/deploySolutionFromTemplate.test.ts
- packages/deployer/test/deploySolutionItems.test.ts
- packages/deployer/test/deployer.test.ts
- packages/simple-types/src/helpers/formHelpers.ts
- packages/workflow/src/workflow.ts
- packages/workflow/src/workflowHelpers.ts
- packages/workflow/test/workflow.test.ts
- packages/workflow/test/workflowHelpers.test.ts
Fix the discovery and handling of the URL to the workflow manager.
Rename variables as needed to better match their purpose after having learned more about workflow manager.
#875
(There are a gazillion commits because I had to isolate a bug occurring only during testing.)
> Revise workflow handling

- packages/common/src/workflowHelpers.ts
- packages/common/test/workflowHelpers.test.ts
checkStatus can throw an error
> Improve check for Workflow Manager access

- packages/common/src/restHelpers.ts
- packages/common/src/workflowHelpers.ts
- packages/common/test/restHelpers.test.ts
- packages/common/test/workflowHelpers.test.ts
- packages/deployer/src/deploySolutionFromTemplate.ts
- packages/deployer/test/deploySolutionFromTemplate.test.ts
Also refactored deploySolutionFromTemplate to use async
> Fixed workflow manager url

- packages/common/src/workflowHelpers.ts
- packages/common/test/workflowHelpers.test.ts
- packages/creator/src/creator.ts
- packages/deployer/src/deploySolutionFromTemplate.ts
- packages/deployer/src/deployer.ts
- packages/deployer/test/deploySolutionFromTemplate.test.ts
- packages/workflow/src/workflow.ts
> Fixed creation of workflow template

- .gitignore
- demos/deploySolution/package.json
- demos/deploySolution/src/authenticate.ts
- demos/deploySolution/src/index.ts
"Should not import the named export 'appId' (imported as 'appConfig') from default-exporting module (only default export is available soon)"
Also simplified authenticate.html
> Removed import of named export

- packages/web-tool/src/web-tool-processor.ts
- packages/web-tool/test/web-tool-processor.test.ts
> Web tool updates

- build.bat
- demos/reuseDeployedItems/README.md
- demos/reuseDeployedItems/index.html
- demos/reuseDeployedItems/package-lock.json
- demos/reuseDeployedItems/package.json
- demos/reuseDeployedItems/src/demoCommon.ts
- demos/reuseDeployedItems/src/getFormattedItemInfo.ts
- demos/reuseDeployedItems/src/htmlUtil.ts
- demos/reuseDeployedItems/src/index.ts
- demos/reuseDeployedItems/src/reuse-deployed-items-main.ts
- demos/reuseDeployedItems/src/style.css
- demos/reuseDeployedItems/tsconfig.json
- demos/reuseDeployedItems/webpack.config.js
- packages/common/src/index.ts
- packages/common/src/item-reuse.ts
- packages/common/test/item-reuse.test.ts
@MikeTschudi this starts the reuse work. They are still working on the UI to support this.
> Item reuse

- packages/common/src/interfaces.ts
- packages/common/src/velocityHelpers.ts
- packages/common/test/mocks/agolItems.ts
- packages/common/test/velocityHelpers.test.ts
backend support for: https://devtopia.esri.com/WebGIS/solutions-development-support/issues/220
> get velocity info

- packages/simple-types/src/notebook.ts
- packages/simple-types/test/helpers/create-item-from-template.test.ts
https://devtopia.esri.com/WebGIS/solution-deployment-apps/issues/172
> resolve template when no ids are found

- packages/common/src/resources/getItemResourcesPaths.ts
- packages/common/src/restHelpersGet.ts
- packages/common/test/mocks/templates.ts
- packages/common/test/resources/getItemResourcesPaths.test.ts
- packages/creator/src/createItemTemplate.ts
- packages/creator/src/helpers/add-content-to-solution.ts
- packages/creator/test/createItemTemplate.test.ts
- packages/simple-types/src/helpers/convert-item-to-template.ts
- packages/simple-types/src/notebook.ts
- packages/simple-types/test/helpers/create-item-from-template.test.ts
- packages/simple-types/test/notebook.test.ts
- packages/web-tool/src/web-tool-processor.ts
> Webtool id check

- packages/common/src/resources/copyAssociatedFiles.ts
Now have two constraints for creating zips for bundling resources for sending up to a solution item:
1. A maximum of 50 files can be added each request. (as before)
2. Each file should be no more than 50 Mb.
[ArcGIS Online doc](https://developers.arcgis.com/rest/users-groups-and-items/add-resources/)
https://devtopia.esri.com/WebGIS/solutions-development-support/issues/287#issuecomment-5058267
> Enhanced constraints for creating zips for uploading resources
